"""add is_closed closed_at closed_by to orders

Revision ID: 2566be302171
Revises: 353afd3c0c34
Create Date: 2026-06-07 11:19:17.551070

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2566be302171"
down_revision: str | None = "353afd3c0c34"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("is_closed", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("orders", sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("orders", sa.Column("closed_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "orders", "employee", ["closed_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "closed_by")
    op.drop_column("orders", "closed_at")
    op.drop_column("orders", "is_closed")
    # ### end Alembic commands ###
